### ISSUE TITLE
Error with Sonar analysis

### ISSUE THREAD

**Issue by camory** [vavr-io/vavr#2008]
I am getting an issue when anaylzing my project with the sonar maven plugin. 
````
[ERROR] [15:48:04.269] Unable to create symbol table for : /path/projetc/src/main/java/my/package/Person.java

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: javaslang/?.class
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147) ~[na:1.8.0_74]
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71) ~[na:1.8.0_74]
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281) ~[na:1.8.0_74]
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53) ~[na:1.8.0_74]
	at org.sonar.java.bytecode.loader.FileSystemLoader.findResource(FileSystemLoader.java:45) ~[java-frontend-4.2.jar:na]
	at org.sonar.java.bytecode.loader.SquidClassLoader.findResource(SquidClassLoader.java:75) ~[java-frontend-4.2.jar:na]
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093) ~[na:1.8.0_74]
````

* Javaslang version: 2.0.6
* sonar-maven-plugin version: 2.6
* SonarQube version: 5.6.2

It seems that the **?.class** is the origin of the issue.

**Comment by nfekete** [comment]
That's the class with an unicode λ as it's name. It got renamed to `Lambda`. Switch to the renamed project `io.vavr:vavr`, it has it's first release as 0.9.0 in the central maven repository.

**Comment by camory** [comment]
Wow !!! So quik that I did not your answer !! 
and it works !! 
Thanks you for your reactivity and for your great work
