### ISSUE TITLE
Stream.extend hangs sometimes

### ISSUE THREAD

**Issue by noel-yap** [vavr-io/vavr#2613]
I'm using `Stream.extend` and have noticed that it hangs sometimes. Following are some of the thread dump snapshots I've taken:

11:20:09
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at Grid$$Lambda$327.370440646.apply(Unknown Source:-1)
	  at io.vavr.collection.Iterator$22.next(Iterator.java:1078)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7bd> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$3.next(Stream.java:1770)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7be> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$StreamIterator$$Lambda$303.2043318969.get(Unknown Source:-1)
	  at io.vavr.collection.Stream$StreamIterator.hasNext(Stream.java:2167)
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:20:31
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2197)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:20:52
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c1> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$3.next(Stream.java:1770)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c2> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$StreamIterator$$Lambda$303.2043318969.get(Unknown Source:-1)
	  at io.vavr.collection.Stream$StreamIterator.hasNext(Stream.java:2167)
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:21:14
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c3> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$3.next(Stream.java:1770)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c4> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$StreamIterator$$Lambda$303.2043318969.get(Unknown Source:-1)
	  at io.vavr.collection.Stream$StreamIterator.hasNext(Stream.java:2167)
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:21:36
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory.lambda$create$0(Stream.java:2153)
	  at io.vavr.collection.Stream$StreamFactory$$Lambda$295.444920847.get(Unknown Source:-1)
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c5> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$StreamIterator$$Lambda$303.2043318969.get(Unknown Source:-1)
	  at io.vavr.collection.Stream$StreamIterator.hasNext(Stream.java:2167)
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:21:57
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

11:22:19
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.vavr.Lazy.computeValue(Lazy.java:166)
	  - locked <0x7c6> (a io.vavr.Lazy)
	  at io.vavr.Lazy.get(Lazy.java:160)
	  at io.vavr.collection.Stream$ConsImpl.tail(Stream.java:1959)
	  at io.vavr.collection.Stream$StreamIterator$$Lambda$303.2043318969.get(Unknown Source:-1)
	  at io.vavr.collection.Stream$StreamIterator.hasNext(Stream.java:2167)
	  at io.vavr.collection.Stream$FlatMapIterator.hasNext(Stream.java:2196)
	  at io.vavr.collection.Stream$StreamFactory.create(Stream.java:2153)
	  at io.vavr.collection.Stream.ofAll(Stream.java:388)
	  at io.vavr.collection.Stream.flatMap(Stream.java:1060)
	  at Grid.findPath(Grid.java:193)
```

What's happening that's causing this?

**Comment by danieldietrich** [comment]
Please provide a minimal working example (MWE) in order to reproduce it. Thx!

**Comment by danieldietrich** [comment]
Closing this issue because it is stale. I can't reproduce it without a MWE.
