### ISSUE TITLE
Array.appendAll throws exception, when trying to work with Enums

### ISSUE THREAD

**Issue by Yuriy-CentricSoftware** [vavr-io/vavr#2781]
JavaSE-21,
vavr 0.10.4,
JUnit 5.10.3

The following unit test throws exception at the second call Array.appendAll:

```
package com.xxx;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import io.vavr.collection.Array;

public class TestSwitch {

    static sealed interface Kind permits ClassKind, TypeKind {
    }

    static enum ClassKind implements Kind {
        A1,
        A2,
        A3;
    }

    static enum TypeKind implements Kind {
        A1,
        A2,
        A3;
    }

    @Test
    void testSwitch() {
        // Setup
        Array<Kind> kinds = Array.<Kind> empty()
                .appendAll(Array.<Kind> of(ClassKind.values()))
                .appendAll(Array.<Kind> of(TypeKind.values()));

        // Execute
        Array<String> result = kinds.map(this::label);

        // Verify
        assertEquals(
                Array.of("Class:A1", "Class:A2", "Class:A3", "Type:A1", "Type:A2", "Type:A3"),
                result);
    }

    String label(Kind kind) {
        return switch (kind) {
            case ClassKind.A1 -> "Class:A1";
            case ClassKind.A2 -> "Class:A2";
            case ClassKind.A3 -> "Class:A3";
            case TypeKind.A1 -> "Type:A1";
            case TypeKind.A2 -> "Type:A2";
            case TypeKind.A3 -> "Type:A3";
            default -> throw new IllegalArgumentException("Unexpected value: " + kind);
        };
    }

}
```

Exception:

```
java.lang.ArrayStoreException: arraycopy: type mismatch: can not copy com.xxx.TestSwitch$TypeKind[] into com.xxx.TestSwitch$ClassKind[]
	at java.base/java.lang.System.arraycopy(Native Method)
	at io.vavr.collection.Array.appendAll(Array.java:625)
	at com.xxx.TestSwitch.testSwitch(TestSwitch.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```

**Comment by pivovarit** [comment]
I managed to reproduce it. Thanks! Fix incoming in 0.10.5. As soon as possible, hopefully.
